spring:
  application:
    name: ${project.artifactId}
    version: ${project.version}
    namespace: ${banchile.system.namespace}
    
server:
  port: 80

logging:
  level:
    org.springframework: INFO
    cl.banchile: INFO
